// AUTO-GENERATED BY SCRIPT

export enum WorkspaceMemberRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

export enum WorkspaceMemberStatus {
  ACTIVE = 'ACTIVE',
  INVITED = 'INVITED',
  SUSPENDED = 'SUSPENDED',
}

export enum ClientStatus {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum ProjectStatus {
  PLANNING = 'PLANNING',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_ON_CLIENT = 'WAITING_ON_CLIENT',
  IN_REVIEW = 'IN_REVIEW',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
}

export enum ProjectMemberRole {
  LEAD = 'LEAD',
  MEMBER = 'MEMBER',
}

export enum MilestoneStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_ON_CLIENT = 'WAITING_ON_CLIENT',
  COMPLETED = 'COMPLETED',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  BLOCKED = 'BLOCKED',
  DONE = 'DONE',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum DeliverableStatus {
  DRAFT = 'DRAFT',
  IN_REVIEW = 'IN_REVIEW',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  APPROVED = 'APPROVED',
  ARCHIVED = 'ARCHIVED',
}

export enum DeliverableVersionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  APPROVED = 'APPROVED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum CommentStatus {
  OPEN = 'OPEN',
  RESOLVED = 'RESOLVED',
}

export enum ApprovalDecision {
  APPROVED = 'APPROVED',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
}

export enum MessageType {
  TEXT = 'TEXT',
  SYSTEM = 'SYSTEM',
}

export enum NotificationType {
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  DELIVERABLE_SUBMITTED = 'DELIVERABLE_SUBMITTED',
  FEEDBACK_RECEIVED = 'FEEDBACK_RECEIVED',
  APPROVAL_RECEIVED = 'APPROVAL_RECEIVED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  MILESTONE_COMPLETED = 'MILESTONE_COMPLETED',
  INVITATION = 'INVITATION',
  MENTION = 'MENTION',
  GENERAL = 'GENERAL',
}

export enum FileOwnerType {
  DELIVERABLE_VERSION = 'DELIVERABLE_VERSION',
  MESSAGE = 'MESSAGE',
  INVOICE = 'INVOICE',
  PROJECT = 'PROJECT',
  WORKSPACE = 'WORKSPACE',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  VIEWED = 'VIEWED',
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  OVERDUE = 'OVERDUE',
  VOID = 'VOID',
}

export enum ActivityAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  ARCHIVED = 'ARCHIVED',
  RESTORED = 'RESTORED',
  INVITED = 'INVITED',
  ACCEPTED = 'ACCEPTED',
  ADDED = 'ADDED',
  REMOVED = 'REMOVED',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  COMMENTED = 'COMMENTED',
  MESSAGED = 'MESSAGED',
  COMPLETED = 'COMPLETED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  UPLOADED = 'UPLOADED',
  DOWNLOADED = 'DOWNLOADED',
  VIEWED = 'VIEWED',
}

export enum ActivityEntityType {
  WORKSPACE = 'WORKSPACE',
  MEMBER = 'MEMBER',
  CLIENT = 'CLIENT',
  PROJECT = 'PROJECT',
  MILESTONE = 'MILESTONE',
  TASK = 'TASK',
  DELIVERABLE = 'DELIVERABLE',
  DELIVERABLE_VERSION = 'DELIVERABLE_VERSION',
  COMMENT = 'COMMENT',
  APPROVAL = 'APPROVAL',
  MESSAGE = 'MESSAGE',
  FILE = 'FILE',
  INVOICE = 'INVOICE',
}

export interface User {
  id: string;
  email: string;
  passwordHash?: string;
  firstName: string;
  lastName: string;
  avatarUrl?: string;
  timezone: string;
  emailVerifiedAt?: Date | string;
  lastLoginAt?: Date | string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  memberships: WorkspaceMember[];
  ownedWorkspaces: Workspace[];
  invitationsSent: Invitation[];
  projectMemberships: ProjectMember[];
  assignedTasks: Task[];
  createdTasks: Task[];
  comments: DeliverableComment[];
  approvals: Approval[];
  messages: Message[];
  notifications: Notification[];
  activities: Activity[];
  uploadedFiles: File[];
  clientContact?: ClientContact;
}

export interface Workspace {
  id: string;
  name: string;
  slug: string;
  ownerId: string;
  logoUrl?: string;
  description?: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  owner: User;
  fields: [ownerId];
  references:[id];
  onDelete: Restrict;
  onUpdate: Cascade;
  members: WorkspaceMember[];
  invitations: Invitation[];
  clients: Client[];
  projects: Project[];
  files: File[];
  invoices: Invoice[];
  activities: Activity[];
}

export interface WorkspaceMember {
  id: string;
  workspaceId: string;
  userId: string;
  role: WorkspaceMemberRole;
  status: WorkspaceMemberStatus;
  joinedAt?: Date | string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  workspace: Workspace;
  user: User;
  fields: [userId];
  references: [id];
  onDelete: Cascade;
  onUpdate: Cascade;
}

export interface Invitation {
  id: string;
  workspaceId: string;
  inviterId: string;
  email: string;
  role: WorkspaceMemberRole;
  tokenHash: string;
  status: InvitationStatus;
  expiresAt: Date | string;
  acceptedAt?: Date | string;
  createdAt: Date | string;
  updatedAt: Date | string;
  workspace: Workspace;
  fields:: [workspaceId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  inviter: User;
  fields:: [inviterId],;
  references:: [id],;
  onDelete:: Restrict,;
  onUpdate:: Cascade;
}

export interface Client {
  id: string;
  workspaceId: string;
  name: string;
  email?: string;
  company?: string;
  phone?: string;
  status: ClientStatus;
  notes?: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  workspace: Workspace;
  fields:: [workspaceId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  projects: Project[];
  invoices: Invoice[];
  contacts: ClientContact[];
}

export interface ClientContact {
  id: string;
  clientId: string;
  userId: string;
  isPrimary: boolean;
  createdAt: Date | string;
  updatedAt: Date | string;
  client: Client;
  fields:: [clientId],;
  references:: [id],;
  onDelete:: Cascade;
  user: User;
  fields:: [userId],;
  references:: [id],;
  onDelete:: Cascade;
}

export interface Project {
  id: string;
  workspaceId: string;
  clientId: string;
  name: string;
  slug: string;
  description?: string;
  status: ProjectStatus;
  startDate?: Date | string;
  dueDate?: Date | string;
  completedAt?: Date | string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  workspace: Workspace;
  fields:: [workspaceId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  client: Client;
  fields:: [clientId],;
  references:: [id],;
  onDelete:: Restrict,;
  onUpdate:: Cascade;
  members: ProjectMember[];
  milestones: Milestone[];
  tasks: Task[];
  deliverables: Deliverable[];
  messages: Message[];
  invoices: Invoice[];
  files: File[];
  activities: Activity[];
}

export interface ProjectMember {
  id: string;
  projectId: string;
  userId: string;
  role: ProjectMemberRole;
  createdAt: Date | string;
  updatedAt: Date | string;
  project: Project;
  fields:: [projectId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  user: User;
  fields:: [userId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
}

export interface Milestone {
  id: string;
  projectId: string;
  name: string;
  description?: string;
  position: number;
  status: MilestoneStatus;
  dueDate?: Date | string;
  completedAt?: Date | string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  project: Project;
  fields:: [projectId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  tasks: Task[];
  deliverables: Deliverable[];
}

export interface Task {
  id: string;
  projectId: string;
  milestoneId?: string;
  assigneeId?: string;
  creatorId: string;
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  position: number;
  dueDate?: Date | string;
  completedAt?: Date | string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  project: Project;
  fields:: [projectId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  milestone?: Milestone;
  fields:: [milestoneId],;
  references:: [id],;
  onDelete:: SetNull,;
  onUpdate:: Cascade;
  assignee?: User;
  fields:: [assigneeId],;
  references:: [id],;
  onDelete:: SetNull,;
  onUpdate:: Cascade;
  creator: User;
  fields:: [creatorId],;
  references:: [id],;
  onDelete:: Restrict,;
  onUpdate:: Cascade;
}

export interface Deliverable {
  id: string;
  projectId: string;
  milestoneId?: string;
  name: string;
  description?: string;
  status: DeliverableStatus;
  currentVersionId?: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  project: Project;
  fields:: [projectId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  milestone?: Milestone;
  fields:: [milestoneId],;
  references:: [id],;
  onDelete:: SetNull,;
  onUpdate:: Cascade;
  versions: DeliverableVersion[];
  currentVersion?: DeliverableVersion;
  fields:: [currentVersionId],;
  references:: [id],;
  onDelete:: SetNull,;
  onUpdate:: Cascade;
}

export interface DeliverableVersion {
  id: string;
  deliverableId: string;
  versionNumber: number;
  title?: string;
  description?: string;
  status: DeliverableVersionStatus;
  submittedAt?: Date | string;
  approvedAt?: Date | string;
  changesRequestedAt?: Date | string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  deliverable: Deliverable;
  fields:: [deliverableId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  currentFor?: Deliverable;
  comments: DeliverableComment[];
  approvals: Approval[];
  files: File[];
}

export interface DeliverableComment {
  id: string;
  deliverableVersionId: string;
  authorId: string;
  body: string;
  status: CommentStatus;
  parentCommentId?: string;
  resolvedAt?: Date | string;
  resolvedById?: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  deliverableVersion: DeliverableVersion;
  fields:: [deliverableVersionId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  author: User;
  fields:: [authorId],;
  references:: [id],;
  onDelete:: Restrict,;
  onUpdate:: Cascade;
  parentComment?: DeliverableComment;
  fields:: [parentCommentId],;
  references:: [id],;
  onDelete:: SetNull,;
  onUpdate:: Cascade;
  replies: DeliverableComment[];
}

export interface Approval {
  id: string;
  deliverableVersionId: string;
  reviewerId: string;
  decision: ApprovalDecision;
  note?: string;
  createdAt: Date | string;
  deliverableVersion: DeliverableVersion;
  fields:: [deliverableVersionId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  reviewer: User;
  fields:: [reviewerId],;
  references:: [id],;
  onDelete:: Restrict,;
  onUpdate:: Cascade;
}

export interface Message {
  id: string;
  projectId: string;
  senderId: string;
  type: MessageType;
  body: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  project: Project;
  fields:: [projectId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  sender: User;
  fields:: [senderId],;
  references:: [id],;
  onDelete:: Restrict,;
  onUpdate:: Cascade;
  attachments: File[];
}

export interface File {
  id: string;
  workspaceId: string;
  uploaderId: string;
  projectId?: string;
  messageId?: string;
  deliverableVersionId?: string;
  invoiceId?: string;
  ownerType: FileOwnerType;
  originalName: string;
  storageKey: string;
  mimeType: string;
  sizeBytes: number;
  checksum?: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  workspace: Workspace;
  fields:: [workspaceId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  uploader: User;
  fields:: [uploaderId],;
  references:: [id],;
  onDelete:: Restrict,;
  onUpdate:: Cascade;
  project?: Project;
  fields:: [projectId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  message?: Message;
  fields:: [messageId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  deliverableVersion?: DeliverableVersion;
  fields:: [deliverableVersionId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  invoice?: Invoice;
  fields:: [invoiceId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
}

export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  title: string;
  body: string;
  projectId?: string;
  deliverableId?: string;
  messageId?: string;
  metadata?: any;
  readAt?: Date | string;
  createdAt: Date | string;
  user: User;
  fields:: [userId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
}

export interface Invoice {
  id: string;
  workspaceId: string;
  projectId?: string;
  clientId: string;
  invoiceNumber: string;
  status: InvoiceStatus;
  issueDate: Date | string;
  dueDate: Date | string;
  currency: string;
  subtotal: number;
  tax: number;
  total: number;
  notes?: string;
  sentAt?: Date | string;
  paidAt?: Date | string;
  createdAt: Date | string;
  updatedAt: Date | string;
  deletedAt?: Date | string;
  workspace: Workspace;
  fields:: [workspaceId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  project?: Project;
  fields:: [projectId],;
  references:: [id],;
  onDelete:: SetNull,;
  onUpdate:: Cascade;
  client: Client;
  fields:: [clientId],;
  references:: [id],;
  onDelete:: Restrict,;
  onUpdate:: Cascade;
  items: InvoiceItem[];
  files: File[];
}

export interface InvoiceItem {
  id: string;
  invoiceId: string;
  description: string;
  quantity: number;
  unitPrice: number;
  amount: number;
  position: number;
  createdAt: Date | string;
  updatedAt: Date | string;
  invoice: Invoice;
  fields:: [invoiceId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
}

export interface Activity {
  id: string;
  workspaceId: string;
  actorId?: string;
  action: ActivityAction;
  entityType: ActivityEntityType;
  entityId: string;
  projectId?: string;
  description: string;
  metadata?: any;
  createdAt: Date | string;
  workspace: Workspace;
  fields:: [workspaceId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
  actor?: User;
  fields:: [actorId],;
  references:: [id],;
  onDelete:: SetNull,;
  onUpdate:: Cascade;
  project?: Project;
  fields:: [projectId],;
  references:: [id],;
  onDelete:: Cascade,;
  onUpdate:: Cascade;
}

